version: '6.0.{build}'

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64

install:
  - '%APPVEYOR_BUILD_FOLDER%\scripts\appveyor\install.bat'

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\scripts\appveyor\build.bat'

artifacts:
  - path: llvm_install_6.0.zip
