@echo on

cd "%APPVEYOR_BUILD_FOLDER%"

IF %COMPILER%==msys2 (
  cd "C:\projects"
  mkdir llvm_build
  REM mkdir llvm_install
  cd "C:\projects\llvm_build"
  "C:\Program Files (x86)\cmake\bin\cmake.exe" -G"MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_TARGETS_TO_BUILD="host" -DLLVM_BUILD_TOOLS=true -DLLVM_ENABLE_EH=true -DLLVM_ENABLE_PIC=true -DLLVM_ENABLE_RTTI=true -DLLVM_INCLUDE_TESTS=false -DLLVM_TOOL_BUGPOINT_BUILD=false -DLLVM_TOOL_BUGPOINT_PASSES_BUILD=false -DLLVM_TOOL_CLANG_BUILD=false -DLLVM_TOOL_DSYMUTIL_BUILD=false -DLLVM_TOOL_GOLD_BUILD=false -DLLVM_TOOL_LLC_BUILD=false -DLLVM_TOOL_LLI_BUILD=false -DLLVM_TOOL_LLVM_AR_BUILD=false -DLLVM_TOOL_LLVM_AS_BUILD=false -DLLVM_TOOL_LLVM_AS_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_BCANALYZER_BUILD=false -DLLVM_TOOL_LLVM_COV_BUILD=false -DLLVM_TOOL_LLVM_C_TEST_BUILD=false -DLLVM_TOOL_LLVM_CXXDUMP_BUILD=false -DLLVM_TOOL_LLVM_DIFF_BUILD=false -DLLVM_TOOL_LLVM_DIS_BUILD=false -DLLVM_TOOL_LLVM_DWARFDUMP_BUILD=false -DLLVM_TOOL_LLVM_DWP_BUILD=false -DLLVM_TOOL_LLVM_EXTRACT_BUILD=false -DLLVM_TOOL_LLVM_GO_BUILD=false -DLLVM_TOOL_LLVM_JITLISTENER_BUILD=false -DLLVM_TOOL_LLVM_LINK_BUILD=false -DLLVM_TOOL_LLVM_LTO_BUILD=false -DLLVM_TOOL_LLVM_MC_BUILD=false -DLLVM_TOOL_LLVM_MC_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_MCMARKUP_BUILD=false -DLLVM_TOOL_LLVM_NM_BUILD=false -DLLVM_TOOL_LLVM_OBJDUMP_BUILD=false -DLLVM_TOOL_LLVM_PDBDUMP_BUILD=false -DLLVM_TOOL_LLVM_PROFDATA_BUILD=false -DLLVM_TOOL_LLVM_READOBJ_BUILD=false -DLLVM_TOOL_LLVM_RTDYLD_BUILD=false -DLLVM_TOOL_LLVM_SHLIB_BUILD=false -DLLVM_TOOL_LLVM_SIZE_BUILD=false -DLLVM_TOOL_LLVM_SPLIT_BUILD=false -DLLVM_TOOL_LLVM_STRESS_BUILD=false -DLLVM_TOOL_LLVM_SYMBOLIZER_BUILD=false -DLLVM_TOOL_LTO_BUILD=false -DLLVM_TOOL_MSBUILD_BUILD=false -DLLVM_TOOL_OBJ2YAML_BUILD=false -DLLVM_TOOL_OPT_BUILD=false -DLLVM_TOOL_SANCOV_BUILD=false -DLLVM_TOOL_SANSTATS_BUILD=false -DLLVM_TOOL_VERIFY_USELISTORDER_BUILD=false -DLLVM_TOOL_XCODE_TOOLCHAIN_BUILD=false -DLLVM_TOOL_YAML2OBJ_BUILD=false -DCMAKE_INSTALL_PREFIX="C:\\projects\\llvm_install" %APPVEYOR_BUILD_FOLDER%
  bash "%APPVEYOR_BUILD_FOLDER%\scripts\appveyor\build.sh"
)
